export const LOAD_COMMENTS = 'lOAD_COMMENTS';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const REPLY_COMMENT = 'REPLY_COMMENT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SET_DIMENSIONS = 'SET_DIMENSIONS';
export const UPDATE_LIKES_COMMENT = 'UPDATE_LIKES_COMMENT';
